export const categories: Category[] = [
  {
    id: "c1",
    slug: "פסיכולוגיה-חיובית",
    name: "פסיכולוגיה חיובית",
    description: "כלים למציאת אושר, משמעות וחוסן נפשי בחיי היומיום.",
  },
  {
    id: "c2",
    slug: "תקשורת-בין-אישית",
    name: "תקשורת בין-אישית",
    description: "אמנות השיחה, הקשבה עמוקה ובניית גשרים בין אנשים.",
  },
  {
    id: "c3",
    slug: "שפת-גוף",
    name: "שפת גוף",
    description: "פענוח המסרים הבלתי מילוליים שעוברים מתחת לרדאר.",
  },
  {
    id: "c4",
    slug: "חרדה-וחוסן-רגשי",
    name: "חרדה וחוסן רגשי",
    description: "הבנת מנגנוני הפחד ופיתוח כלים להתמודדות עם לחצים.",
  },
  {
    id: "c5",
    slug: "זוגיות-ומערכות-יחסים",
    name: "זוגיות ומערכות יחסים",
    description: "דינמיקה זוגית, שימור התשוקה ובניית אמון ארוך טווח.",
  },
  {
    id: "c6",
    slug: "פסיכולוגיה-של-הצלחה",
    name: "פסיכולוגיה של הצלחה",
    description: "שינוי דפוסי חשיבה להשגת מטרות ומיצוי הפוטנציאל האישי.",
  },
  {
    id: "c7",
    slug: "הורות-ומודעות",
    name: "הורות ומודעות",
    description: "גישות פסיכולוגיות בגידול ילדים ושיפור הקשר ההורי.",
  },
  {
    id: "c8",
    slug: "ניהול-קונפליקטים",
    name: "ניהול קונפליקטים",
    description: "איך להפוך מריבות להזדמנויות לצמיחה והבנה הדדית.",
  },
];

export const posts: PostPreview[] = [
  {
    id: "p1",
    category_id: "c1",
    slug: "פסיכולוגיה-חיובית/כוחה-של-הכרת-תודה",
    published: true,
    updated_at: "2024-01-10",
    title: "כוחה של הכרת תודה",
    sub_title: "איך תרגול יומי משנה את המוח",
    views: 1200,
    likes: 450,
  },
  {
    id: "p2",
    category_id: "c1",
    slug: "פסיכולוגיה-חיובית/מציאת-משמעות-בעבודה",
    published: true,
    updated_at: "2024-01-12",
    title: "מציאת משמעות בעבודה",
    sub_title: "מעבר לפרנסה - איך להרגיש סיפוק",
    views: 890,
    likes: 310,
  },
  {
    id: "p3",
    category_id: "c1",
    slug: "פסיכולוגיה-חיובית/חשיבות-האופטימיות-הזהירה",
    published: true,
    updated_at: "2024-01-15",
    title: "חשיבות האופטימיות הזהירה",
    sub_title: "למה חשוב לראות את הטוב בלי להתעלם מהמציאות",
    views: 1500,
    likes: 620,
  },
  {
    id: "p4",
    category_id: "c1",
    slug: "פסיכולוגיה-חיובית/חוסן-נפשי-בעת-משבר",
    published: true,
    updated_at: "2024-01-18",
    title: "חוסן נפשי בעת משבר",
    sub_title: "איך לקום מהקרקע חזקים יותר",
    views: 2300,
    likes: 980,
  },
  {
    id: "p5",
    category_id: "c1",
    slug: "פסיכולוגיה-חיובית/מיינדפולנס-למתחילים",
    published: true,
    updated_at: "2024-01-20",
    title: "מיינדפולנס למתחילים",
    sub_title: "להיות כאן ועכשיו בתוך עולם רועש",
    views: 3400,
    likes: 1100,
  },
  {
    id: "p6",
    category_id: "c1",
    slug: "פסיכולוגיה-חיובית/הפסיכולוגיה-של-החיוך",
    published: true,
    updated_at: "2024-01-22",
    title: "הפסיכולוגיה של החיוך",
    sub_title: "האם חיוך מאולץ באמת יכול לשפר מצב רוח?",
    views: 1100,
    likes: 400,
  },
  {
    id: "p7",
    category_id: "c1",
    slug: "פסיכולוגיה-חיובית/סליחה-עצמית",
    published: true,
    updated_at: "2024-01-25",
    title: "סליחה עצמית",
    sub_title: "להשתחרר מהעבר כדי לחיות את ההווה",
    views: 1750,
    likes: 820,
  },
  {
    id: "p8",
    category_id: "c1",
    slug: "פסיכולוגיה-חיובית/השפעת-הטבע-על-הנפש",
    published: true,
    updated_at: "2024-01-28",
    title: "השפעת הטבע על הנפש",
    sub_title: "למה טיול ביער הוא התרופה הכי טובה",
    views: 2100,
    likes: 750,
  },

  {
    id: "p9",
    category_id: "c2",
    slug: "תקשורת-בין-אישית/אמנות-ההקשבה",
    published: true,
    updated_at: "2024-02-01",
    title: "אמנות ההקשבה",
    sub_title: "ההבדל בין לשמוע לבין באמת להבין",
    views: 2800,
    likes: 940,
  },
  {
    id: "p10",
    category_id: "c2",
    slug: "תקשורת-בין-אישית/שאלות-שפותחות-לבבות",
    published: true,
    updated_at: "2024-02-03",
    title: "שאלות שפותחות לבבות",
    sub_title: "איך להעמיק קשר בתוך חמש דקות",
    views: 1900,
    likes: 670,
  },
  {
    id: "p11",
    category_id: "c2",
    slug: "תקשורת-בין-אישית/איך-להתמודד-עם-שתיקות-מביכות",
    published: true,
    updated_at: "2024-02-05",
    title: "איך להתמודד עם שתיקות מביכות",
    sub_title: "להפוך רגע מביך להזדמנות לחיבור",
    views: 4200,
    likes: 1300,
  },
  {
    id: "p12",
    category_id: "c2",
    slug: "תקשורת-בין-אישית/כוחן-של-מילים",
    published: true,
    updated_at: "2024-02-07",
    title: "כוחן של מילים",
    sub_title: "איך בחירת מילה אחת משנה את כל המשפט",
    views: 1600,
    likes: 520,
  },
  {
    id: "p13",
    category_id: "c2",
    slug: "תקשורת-בין-אישית/יצירת-כימיה-מיידית",
    published: true,
    updated_at: "2024-02-10",
    title: "יצירת כימיה מיידית",
    sub_title: "סודות הכריזמה הבין-אישית",
    views: 5600,
    likes: 2100,
  },
  {
    id: "p14",
    category_id: "c2",
    slug: "תקשורת-בין-אישית/גבולות-בשיחה",
    published: true,
    updated_at: "2024-02-12",
    title: "גבולות בשיחה",
    sub_title: "איך לעצור שיחה שלא נעימה לנו",
    views: 1300,
    likes: 410,
  },
  {
    id: "p15",
    category_id: "c2",
    slug: "תקשורת-בין-אישית/שיחות-חולין-ככלי-עבודה",
    published: true,
    updated_at: "2024-02-15",
    title: "שיחות חולין ככלי עבודה",
    sub_title: "למה סמול-טוק הוא לא בזבוז זמן",
    views: 2400,
    likes: 880,
  },
  {
    id: "p16",
    category_id: "c2",
    slug: "תקשורת-בין-אישית/אמפתיה-במרחב-הדיגיטלי",
    published: true,
    updated_at: "2024-02-18",
    title: "אמפתיה במרחב הדיגיטלי",
    sub_title: "איך להעביר רגש דרך הודעות טקסט",
    views: 3100,
    likes: 1050,
  },

  {
    id: "p17",
    category_id: "c3",
    slug: "שפת-גוף/סימנים-לביטחון-עצמי",
    published: true,
    updated_at: "2024-02-20",
    title: "סימנים לביטחון עצמי",
    sub_title: "איך לשדר עוצמה בלי להגיד מילה",
    views: 4800,
    likes: 1900,
  },
  {
    id: "p18",
    category_id: "c3",
    slug: "שפת-גוף/האמת-מאחורי-לחיצת-היד",
    published: true,
    updated_at: "2024-02-22",
    title: "האמת מאחורי לחיצת היד",
    sub_title: "מה הלחיצה מספרת על האדם שמולך",
    views: 1500,
    likes: 430,
  },
  {
    id: "p19",
    category_id: "c3",
    slug: "שפת-גוף/הבעות-פנים-בזמן-לחץ",
    published: true,
    updated_at: "2024-02-25",
    title: "הבעות פנים בזמן לחץ",
    sub_title: "איך לזהות מצוקה אצל אחרים",
    views: 2200,
    likes: 760,
  },
  {
    id: "p20",
    category_id: "c3",
    slug: "שפת-גוף/המרחק-האישי-הנכון",
    published: true,
    updated_at: "2024-02-28",
    title: "המרחק האישי הנכון",
    sub_title: "מתי קירבה פיזית הופכת למאיימת",
    views: 1800,
    likes: 610,
  },
  {
    id: "p21",
    category_id: "c3",
    slug: "שפת-גוף/שפת-גוף-בראיונות-עבודה",
    published: true,
    updated_at: "2024-03-01",
    title: "שפת גוף בראיונות עבודה",
    sub_title: "טעויות נפוצות שכולם עושים",
    views: 6700,
    likes: 2500,
  },
  {
    id: "p22",
    category_id: "c3",
    slug: "שפת-גוף/קשר-עין-מנצח",
    published: true,
    updated_at: "2024-03-03",
    title: "קשר עין מנצח",
    sub_title: "איך להביט בלי להבהיל",
    views: 3200,
    likes: 1100,
  },
  {
    id: "p23",
    category_id: "c3",
    slug: "שפת-גוף/ישיבה-דומיננטית",
    published: true,
    updated_at: "2024-03-05",
    title: "ישיבה דומיננטית",
    sub_title: "איך לתפוס מקום בחדר הישיבות",
    views: 2900,
    likes: 920,
  },
  {
    id: "p24",
    category_id: "c3",
    slug: "שפת-גוף/תנועות-ידיים-בזמן-דיבור",
    published: true,
    updated_at: "2024-03-08",
    title: "תנועות ידיים בזמן דיבור",
    sub_title: "איך להשתמש בידיים כדי להדגיש מסרים",
    views: 2500,
    likes: 840,
  },

  {
    id: "p25",
    category_id: "c4",
    slug: "חרדה-וחוסן-רגשי/להבין-את-התקף-החרדה",
    published: true,
    updated_at: "2024-03-10",
    title: "להבין את התקף החרדה",
    sub_title: "מה קורה בגוף כשהפחד משתלט",
    views: 8200,
    likes: 3400,
  },
  {
    id: "p26",
    category_id: "c4",
    slug: "חרדה-וחוסן-רגשי/נשימות-להרגעה",
    published: true,
    updated_at: "2024-03-12",
    title: "נשימות להרגעה",
    sub_title: "טכניקות מעשיות להורדת דופק ברגע",
    views: 5400,
    likes: 2200,
  },
  {
    id: "p27",
    category_id: "c4",
    slug: "חרדה-וחוסן-רגשי/חרדה-חברתית-ומציאות",
    published: true,
    updated_at: "2024-03-15",
    title: "חרדה חברתית ומציאות",
    sub_title: "איך להפסיק לפחד משיפוטיות של אחרים",
    views: 4100,
    likes: 1800,
  },
  {
    id: "p28",
    category_id: "c4",
    slug: "חרדה-וחוסן-רגשי/בניית-שגרה-מייצבת",
    published: true,
    updated_at: "2024-03-18",
    title: "בניית שגרה מייצבת",
    sub_title: "למה סדר יום עוזר לנפש",
    views: 2600,
    likes: 950,
  },
  {
    id: "p29",
    category_id: "c4",
    slug: "חרדה-וחוסן-רגשי/כתיבה-טיפולית",
    published: true,
    updated_at: "2024-03-20",
    title: "כתיבה טיפולית",
    sub_title: "איך להוציא את המחשבות מהראש לדף",
    views: 1950,
    likes: 720,
  },
  {
    id: "p30",
    category_id: "c4",
    slug: "חרדה-וחוסן-רגשי/שינה-ובריאות-הנפש",
    published: true,
    updated_at: "2024-03-22",
    title: "שינה ובריאות הנפש",
    sub_title: "הקשר ההדוק בין חוסר שינה לחרדה",
    views: 3700,
    likes: 1400,
  },
  {
    id: "p31",
    category_id: "c4",
    slug: "חרדה-וחוסן-רגשי/חשיפה-הדרגתית",
    published: true,
    updated_at: "2024-03-25",
    title: "חשיפה הדרגתית",
    sub_title: "לנצח את הפחד צעד אחר צעד",
    views: 2100,
    likes: 880,
  },
  {
    id: "p32",
    category_id: "c4",
    slug: "חרדה-וחוסן-רגשי/חשיבות-הטיפול",
    published: true,
    updated_at: "2024-03-28",
    title: "חשיבות הטיפול",
    sub_title: "מתי כדאי לפנות לעזרה מקצועית",
    views: 1500,
    likes: 640,
  },

  {
    id: "p33",
    category_id: "c5",
    slug: "זוגיות-ומערכות-יחסים/בניית-אמון-מחדש",
    published: true,
    updated_at: "2024-04-01",
    title: "בניית אמון מחדש",
    sub_title: "האם אפשר לתקן קשר שנשבר?",
    views: 5900,
    likes: 2100,
  },
  {
    id: "p34",
    category_id: "c5",
    slug: "זוגיות-ומערכות-יחסים/שפות-האהבה-שלנו",
    published: true,
    updated_at: "2024-04-03",
    title: "שפות האהבה שלנו",
    sub_title: "איך כל אחד מאיתנו מבקש אהבה",
    views: 7200,
    likes: 3100,
  },
  {
    id: "p35",
    category_id: "c5",
    slug: "זוגיות-ומערכות-יחסים/מריבות-בונות",
    published: true,
    updated_at: "2024-04-05",
    title: "מריבות בונות",
    sub_title: "איך להתווכח בצורה שמחזקת את הקשר",
    views: 3400,
    likes: 1200,
  },
  {
    id: "p36",
    category_id: "c5",
    slug: "זוגיות-ומערכות-יחסים/אינטימיות-רגשית",
    published: true,
    updated_at: "2024-04-08",
    title: "אינטימיות רגשית",
    sub_title: "מעבר למגע - חיבור הנשמות",
    views: 2800,
    likes: 980,
  },
  {
    id: "p37",
    category_id: "c5",
    slug: "זוגיות-ומערכות-יחסים/חשיבות-המרחב-האישי",
    published: true,
    updated_at: "2024-04-10",
    title: "חשיבות המרחב האישי",
    sub_title: "למה חשוב לשמור על 'אני' בתוך ה'אנחנו'",
    views: 4100,
    likes: 1500,
  },
  {
    id: "p38",
    category_id: "c5",
    slug: "זוגיות-ומערכות-יחסים/זוגיות-בעידן-הדיגיטלי",
    published: true,
    updated_at: "2024-04-12",
    title: "זוגיות בעידן הדיגיטלי",
    sub_title: "איך האינסטגרם משפיע על הקשר שלנו",
    views: 5200,
    likes: 1900,
  },
  {
    id: "p39",
    category_id: "c5",
    slug: "זוגיות-ומערכות-יחסים/בחירת-בן-זוג",
    published: true,
    updated_at: "2024-04-15",
    title: "בחירת בן זוג",
    sub_title: "למה אנחנו נמשכים לאנשים שפוגעים בנו?",
    views: 8900,
    likes: 4200,
  },
  {
    id: "p40",
    category_id: "c5",
    slug: "זוגיות-ומערכות-יחסים/החיים-אחרי-פרידה",
    published: true,
    updated_at: "2024-04-18",
    title: "החיים אחרי פרידה",
    sub_title: "ללמוד ללכת לבד שוב",
    views: 6300,
    likes: 2500,
  },

  {
    id: "p41",
    category_id: "c6",
    slug: "פסיכולוגיה-של-הצלחה/שינוי-הרגלים",
    published: true,
    updated_at: "2024-04-20",
    title: "שינוי הרגלים",
    sub_title: "איך לבנות הרגל חדש ב-21 יום",
    views: 4500,
    likes: 1800,
  },
  {
    id: "p42",
    category_id: "c6",
    slug: "פסיכולוגיה-של-הצלחה/התמודדות-עם-דחיינות",
    published: true,
    updated_at: "2024-04-22",
    title: "התמודדות עם דחיינות",
    sub_title: "למה אנחנו מחכים לרגע האחרון?",
    views: 9100,
    likes: 3800,
  },
  {
    id: "p43",
    category_id: "c6",
    slug: "פסיכולוגיה-של-הצלחה/ניהול-זמן-או-ניהול-אנרגיה",
    published: true,
    updated_at: "2024-04-25",
    title: "ניהול זמן או ניהול אנרגיה",
    sub_title: "מה באמת גורם לנו להספיק יותר",
    views: 3200,
    likes: 1100,
  },
  {
    id: "p44",
    category_id: "c6",
    slug: "פסיכולוגיה-של-הצלחה/הפחד-מכישלון",
    published: true,
    updated_at: "2024-04-28",
    title: "הפחד מכישלון",
    sub_title: "איך להפוך כישלון למקפצה",
    views: 2700,
    likes: 950,
  },
  {
    id: "p45",
    category_id: "c6",
    slug: "פסיכולוגיה-של-הצלחה/חשיבה-יצירתית",
    published: true,
    updated_at: "2024-05-01",
    title: "חשיבה יצירתית",
    sub_title: "איך לייצר רעיונות חדשים בכל יום",
    views: 1800,
    likes: 620,
  },
  {
    id: "p46",
    category_id: "c6",
    slug: "פסיכולוגיה-של-הצלחה/כוח-הרצון",
    published: true,
    updated_at: "2024-05-03",
    title: "כוח הרצון",
    sub_title: "האם זה משאב מוגבל?",
    views: 2400,
    likes: 880,
  },
  {
    id: "p47",
    category_id: "c6",
    slug: "פסיכולוגיה-של-הצלחה/הגדרת-מטרות-נכונה",
    published: true,
    updated_at: "2024-05-05",
    title: "הגדרת מטרות נכונה",
    sub_title: "שיטת SMART ואיך ליישם אותה",
    views: 3900,
    likes: 1400,
  },
  {
    id: "p48",
    category_id: "c6",
    slug: "פסיכולוגיה-של-הצלחה/הפסיכולוגיה-של-הכסף",
    published: true,
    updated_at: "2024-05-08",
    title: "הפסיכולוגיה של הכסף",
    sub_title: "מה היחס שלנו לממון אומר עלינו",
    views: 5700,
    likes: 2300,
  },

  {
    id: "p49",
    category_id: "c7",
    slug: "הורות-ומודעות/הצבת-גבולות-לילדים",
    published: true,
    updated_at: "2024-05-10",
    title: "הצבת גבולות לילדים",
    sub_title: "איך להגיד לא ולהישאר בחיים",
    views: 6800,
    likes: 2900,
  },
  {
    id: "p50",
    category_id: "c7",
    slug: "הורות-ומודעות/הורות-קשובה",
    published: true,
    updated_at: "2024-05-12",
    title: "הורות קשובה",
    sub_title: "להיות נוכחים ברגעים הקטנים",
    views: 3200,
    likes: 1100,
  },
  {
    id: "p51",
    category_id: "c7",
    slug: "הורות-ומודעות/גיל-ההתבגרות-המדריך-להורה",
    published: true,
    updated_at: "2024-05-15",
    title: "גיל ההתבגרות: המדריך להורה",
    sub_title: "לשרוד את הסערה הרגשית",
    views: 4500,
    likes: 1800,
  },
  {
    id: "p52",
    category_id: "c7",
    slug: "הורות-ומודעות/אינטליגנציה-רגשית-אצל-ילדים",
    published: true,
    updated_at: "2024-05-18",
    title: "אינטליגנציה רגשית אצל ילדים",
    sub_title: "איך ללמד ילד לזהות רגשות",
    views: 2900,
    likes: 1050,
  },
  {
    id: "p53",
    category_id: "c7",
    slug: "הורות-ומודעות/השפעת-המסכים-על-הילד",
    published: true,
    updated_at: "2024-05-20",
    title: "השפעת המסכים על הילד",
    sub_title: "כמה זה יותר מדי?",
    views: 7600,
    likes: 3200,
  },
  {
    id: "p54",
    category_id: "c7",
    slug: "הורות-ומודעות/זמן-איכות-אמיתי",
    published: true,
    updated_at: "2024-05-22",
    title: "זמן איכות אמיתי",
    sub_title: "מה ילדים באמת זוכרים",
    views: 2100,
    likes: 890,
  },
  {
    id: "p55",
    category_id: "c7",
    slug: "הורות-ומודעות/הורות-ללא-אשמה",
    published: true,
    updated_at: "2024-05-25",
    title: "הורות ללא אשמה",
    sub_title: "לשחרר את הציפייה להיות הורה מושלם",
    views: 3800,
    likes: 1600,
  },
  {
    id: "p56",
    category_id: "c7",
    slug: "הורות-ומודעות/קנאת-אחים",
    published: true,
    updated_at: "2024-05-28",
    title: "קנאת אחים",
    sub_title: "איך לנהל את המלחמה בבית",
    views: 4200,
    likes: 1700,
  },

  {
    id: "p57",
    category_id: "c8",
    slug: "ניהול-קונפליקטים/תקשורת-מקרבת-בבית",
    published: true,
    updated_at: "2024-06-01",
    title: "תקשורת מקרבת בבית",
    sub_title: "לדבר על צרכים במקום על האשמות",
    views: 3300,
    likes: 1400,
  },
  {
    id: "p58",
    category_id: "c8",
    slug: "ניהול-קונפליקטים/איך-לבקש-סליחה",
    published: true,
    updated_at: "2024-06-03",
    title: "איך לבקש סליחה",
    sub_title: "ארבעת המרכיבים של התנצלות כנה",
    views: 1900,
    likes: 650,
  },
  {
    id: "p59",
    category_id: "c8",
    slug: "ניהול-קונפליקטים/התמודדות-עם-אנשים-קשים",
    published: true,
    updated_at: "2024-06-05",
    title: "התמודדות עם אנשים קשים",
    sub_title: "לשמור על רוגע מול תוקפנות",
    views: 8700,
    likes: 4100,
  },
  {
    id: "p60",
    category_id: "c8",
    slug: "ניהול-קונפליקטים/גישור-עצמי",
    published: true,
    updated_at: "2024-06-08",
    title: "גישור עצמי",
    sub_title: "איך לפתור מחלוקת בלי צד שלישי",
    views: 2200,
    likes: 820,
  },
];
